import Link from 'next/link';
import {ArrowRight,BrainCircuit,CheckCircle2,FileText,ShieldCheck,ScanEye,Activity} from 'lucide-react';
import {Reveal} from '../components/Reveal';
import {ClinicalIllustration} from '../components/ClinicalIllustration';
export default function Home(){return <>
 <section className="hero"><div><div className="eyebrow">AI-ASSISTED RETINAL DECISION SUPPORT</div><h1>See the signal.<br/><span>Explain the result.</span></h1><p>eyeQ connects your trained MATLAB pipeline with a focused clinical workspace for retinal image quality assessment, diabetic retinopathy grading and explainable evidence.</p><div className="actions"><Link href="/screening" className="btn primary">Start a screening <ArrowRight size={16}/></Link><Link href="/how-it-works" className="btn secondary">Explore the pipeline</Link></div><div className="hero-meta"><div><CheckCircle2 size={15}/><span><strong>5-class</strong> ICDR grading</span></div><div><Activity size={15}/><span><strong>Quality</strong> gate before inference</span></div><div><BrainCircuit size={15}/><span><strong>XAI</strong> evidence layer</span></div></div></div><div className="hero-visual"><ClinicalIllustration/><div className="floating-card top float"><span className="dot"/>Model bridge<strong>MATLAB + Flask ready</strong></div><div className="floating-card bottom float"><span className="dot"/>Screening output<strong>Grade · Confidence · Evidence</strong></div></div></section>
 <div className="trustbar"><div className="trustinner"><div className="trustitem"><ShieldCheck size={18}/><span><b>Quality first</b><br/>Poor captures can be flagged</span></div><div className="trustitem"><ScanEye size={18}/><span><b>Explainable</b><br/>Grad-CAM and lesion cues</span></div><div className="trustitem"><BrainCircuit size={18}/><span><b>Model connected</b><br/>Your MATLAB inference pipeline</span></div><div className="trustitem"><FileText size={18}/><span><b>Structured reports</b><br/>Charts and printable PDF</span></div></div></div>
 <section className="section"><Reveal><div className="sectionhead"><div className="eyebrow">CLINICAL WORKSPACE</div><h2>Everything important, without the clutter.</h2><p>The interface keeps the screening flow simple while preserving the model outputs needed for review.</p></div></Reveal><div className="cards"><Reveal><div className="card"><div className="icon"><ShieldCheck/></div><h3>Image quality</h3><p>Surface the quality score and feedback before a clinician relies on a grading result.</p></div></Reveal><Reveal delay={.07}><div className="card"><div className="icon"><BrainCircuit/></div><h3>Prediction + confidence</h3><p>Show the predicted ICDR grade, calibrated confidence, referable signal and complete class distribution.</p></div></Reveal><Reveal delay={.14}><div className="card"><div className="icon"><ScanEye/></div><h3>XAI evidence</h3><p>Keep the original, preprocessed image, Grad-CAM, lesion evidence and narrative in one report.</p></div></Reveal></div></section>
 <section className="section soft"><div className="sectionhead"><div className="eyebrow">PIPELINE</div><h2>From fundus image to an inspectable report.</h2></div><div className="pipeline">{[['01','Capture','Upload a JPG or PNG fundus image.'],['02','Quality gate','Check sharpness, illumination and field of view.'],['03','Inference','Run the trained MATLAB grading pipeline.'],['04','Evidence','Render probabilities, XAI and report outputs.']].map(([n,t,d])=><div className="pipeline-step" key={n}><b>{n}</b><strong>{t}</strong><span>{d}</span></div>)}</div></section>
 <section className="cta"><div><h2>Ready to inspect a retinal image?</h2><p>Open a new screening and send the image through the connected MATLAB pipeline.</p></div><Link href="/screening" className="btn light">New screening <ArrowRight size={16}/></Link></section>
 </>}
